const wordGenreArray = [
  ["air", "gas"],
  ["alarm", "device"],
  ["apricot", "fruit"],
  ["apron", "clothing"],
  ["arrow", "weapon"],
  ["art", "subject"],
  ["atom", "science"],
  ["avocado", "fruit"],
  ["axe", "tool"],
  ["bake", "action"],
  ["bark", "sound"],
  ["barrel", "container"],
  ["basket", "container"],
  ["beard", "body part"],
  ["beet", "vegetable"],
  ["bell", "instrument"],
  ["berry", "fruit"],
  ["biscuit", "food"],
  ["blanket", "clothing"],
  ["blossom", "plant"],
  ["bowl", "container"],
  ["brass", "material"],
  ["brush", "tool"],
  ["cake", "food"],
  ["cap", "clothing"],
  ["cattle", "animal"],
  ["cherry", "fruit"],
  ["chocolate", "food"],
  ["clap", "action"],
  ["clay", "material"],
  ["clutch", "accessory"],
  ["cocoa", "food"],
  ["comb", "tool"],
  ["cone", "shape"],
  ["cooler", "device"],
  ["cotton", "material"],
  ["cucumber", "vegetable"],
  ["cushion", "object"],
  ["dancer", "person"],
  ["dewdrop", "nature"],
  ["doughnut", "food"],
  ["dune", "landform"],
  ["eggplant", "vegetable"],
  ["elder", "person"],
  ["elbow", "body part"],
  ["fern", "plant"],
  ["fleece", "material"],
  ["flour", "ingredient"],
  ["flute", "instrument"],
  ["frypan", "tool"],
  ["gale", "weather"],
  ["garlic", "vegetable"],
  ["gavel", "tool"],
  ["giant", "myth"],
  ["glacier", "nature"],
  ["gleam", "light"],
  ["glitter", "material"],
  ["gourd", "plant"],
  ["grain", "food"],
  ["grapefruit", "fruit"],
  ["gravel", "material"],
  ["hatch", "action"],
  ["hay", "material"],
  ["heat", "energy"],
  ["honeycomb", "nature"],
  ["hose", "tool"],
  ["huddle", "action"],
  ["icebox", "device"],
  ["inkling", "thought"],
  ["jam", "food"],
  ["jewel", "object"],
  ["jive", "dance"],
  ["jungle", "place"],
  ["kite", "toy"],
  ["kitchen", "place"],
  ["knot", "object"],
  ["lamb", "animal"],
  ["lamp", "object"],
  ["lava", "nature"],
  ["leak", "problem"],
  ["leek", "vegetable"],
  ["lilac", "plant"],
  ["lizard", "animal"],
  ["lotion", "product"],
  ["maze", "structure"],
  ["mop", "tool"],
  ["mushroom", "fungus"],
  ["napkin", "object"],
  ["nectar", "food"],
  ["nectarine", "fruit"],
  ["nest", "structure"],
  ["nugget", "object"],
  ["oat", "grain"],
  ["orange", "fruit"],
  ["ostrich", "animal"],
  ["pail", "container"],
  ["pan", "tool"],
  ["peach", "fruit"],
  ["pear", "fruit"],
  ["peas", "vegetable"],
  ["petal", "plant"],
  ["pie", "food"],
  ["plum", "fruit"],
  ["poppy", "plant"],
  ["potato", "vegetable"],
  ["quilt", "object"],
  ["quokka", "animal"],
  ["rattle", "instrument"],
  ["reel", "tool"],
  ["reindeer", "animal"],
  ["rice", "food"],
  ["robin", "animal"],
  ["sack", "object"],
  ["sail", "equipment"],
  ["salad", "food"],
  ["salmon", "animal"],
  ["scent", "perception"],
  ["scissors", "tool"],
  ["scoop", "tool"],
  ["seed", "plant"],
  ["shears", "tool"],
  ["shoe", "clothing"],
  ["silo", "structure"],
  ["skirt", "clothing"],
  ["sleeve", "clothing"],
  ["sling", "object"],
  ["soda", "beverage"],
  ["spice", "food"],
  ["spinach", "vegetable"],
  ["sponge", "object"],
  ["squash", "vegetable"],
  ["straw", "material"],
  ["sugar", "food"],
  ["taco", "food"],
  ["tank", "vehicle"],
  ["tart", "food"],
  ["tide", "nature"],
  ["tidepool", "nature"],
  ["toaster", "device"],
  ["tobacco", "plant"],
  ["tome", "book"],
  ["tornado", "weather"],
  ["tray", "object"],
  ["treat", "food"],
  ["tub", "object"],
  ["tuna", "animal"],
  ["tweezers", "tool"],
  ["vanilla", "flavor"],
  ["vinegar", "food"],
  ["vulture", "animal"],
  ["waddle", "action"],
  ["walnut", "nut"],
  ["whisk", "tool"],
  ["whistle", "instrument"],
  ["whisker", "body part"],
  ["yarn", "material"],
  ["yoke", "tool"],
  ["zest", "food"],
  ["zucchini", "vegetable"],
  ["angel", "myth"],
  ["antler", "body part"],
  ["apartment", "place"],
  ["arch", "structure"],
  ["ash", "material"],
  ["asteroid", "space"],
  ["avalanche", "natural disaster"],
  ["azalea", "plant"],
  ["badge", "object"],
  ["balcony", "structure"],
  ["banana", "fruit"],
  ["bark", "sound"],
  ["basketball", "sport"],
  ["bat", "animal"],
  ["beachball", "toy"],
  ["beetle", "animal"],
  ["berry", "fruit"],
  ["biscuit", "food"],
  ["blackberry", "fruit"],
  ["blueberry", "fruit"],
  ["bottle", "object"],
  ["bowl", "container"],
  ["branch", "plant"],
  ["cactus", "plant"],
  ["calm", "emotion"],
  ["candle", "object"],
  ["canyon", "landform"],
  ["carrot", "vegetable"],
  ["cereal", "food"],
  ["chickpea", "food"],
  ["cob", "object"],
  ["copper", "material"],
  ["cowboy", "person"],
  ["cucumber", "vegetable"],
  ["daisy", "plant"],
  ["doll", "toy"],
  ["doorbell", "device"],
  ["dragonfly", "animal"],
  ["dust", "material"],
  ["egg", "food"],
  ["eyebrow", "body part"],
  ["fig", "fruit"],
  ["flap", "action"],
  ["flour", "ingredient"],
  ["foam", "material"],
  ["frog", "animal"],
  ["fruitcake", "food"],
  ["germ", "biological"],
  ["gravy", "food"],
  ["grin", "expression"],
  ["grit", "material"],
  ["gumdrop", "food"],
  ["hammock", "object"],
  ["hen", "animal"],
  ["honey", "food"],
  ["hops", "plant"],
  ["iceberg", "nature"],
  ["igloo", "structure"],
  ["island", "place"],
  ["jacket", "clothing"],
  ["jellybean", "food"],
  ["jigsaw", "game"],
  ["juice", "beverage"],
  ["kettle", "device"],
  ["knack", "skill"],
  ["knuckle", "body part"],
  ["lamb", "animal"],
  ["lighthouse", "structure"],
  ["lime", "fruit"],
  ["lizard", "animal"],
  ["loaf", "food"],
  ["maple", "tree"],
  ["melon", "fruit"],
  ["mint", "plant"],
  ["moonlight", "nature"],
  ["moth", "animal"],
  ["nap", "action"],
  ["needle", "tool"],
  ["nutmeg", "spice"],
  ["orchard", "place"],
  ["oyster", "animal"],
  ["pancake", "food"],
  ["pebble", "object"],
  ["penguin", "animal"],
  ["pepper", "spice"],
  ["pizza", "food"],
  ["plank", "material"],
  ["plush", "material"],
  ["pocket", "clothing"],
  ["popcorn", "food"],
  ["raccoon", "animal"],
  ["rain", "weather"],
  ["ribbon", "material"],
  ["rock", "material"],
  ["sage", "plant"],
  ["salmon", "animal"],
  ["scone", "food"],
  ["seal", "animal"],
  ["sheepdog", "animal"],
  ["shoehorn", "tool"],
  ["snowflake", "nature"],
  ["snowman", "object"],
  ["sprout", "plant"],
  ["squash", "vegetable"],
  ["squid", "animal"],
  ["squirrel", "animal"],
  ["sweater", "clothing"],
  ["swirl", "action"],
  ["tangle", "action"],
  ["tiger", "animal"],
  ["tulip", "plant"],
  ["valve", "mechanism"],
  ["vortex", "nature"],
  ["waterfall", "nature"],
  ["whale", "animal"],
  ["whisk", "tool"],
  ["wig", "clothing"],
  ["wolverine", "animal"],
  ["yogurt", "food"],
  ["zucchini", "vegetable"],
  ["baby", "person"],
  ["balloon", "object"],
  ["beach", "place"],
  ["bear", "animal"],
  ["bread", "food"],
  ["breeze", "weather"],
  ["brother", "person"],
  ["bubble", "object"],
  ["butter", "food"],
  ["button", "object"],
  ["candy", "food"],
  ["carpet", "material"],
  ["carrot", "vegetable"],
  ["chalk", "material"],
  ["chicken", "animal"],
  ["circle", "shape"],
  ["clock", "object"],
  ["cloud", "nature"],
  ["cookie", "food"],
  ["crayon", "object"],
  ["cupcake", "food"],
  ["cushion", "object"],
  ["dance", "action"],
  ["dirt", "material"],
  ["dish", "object"],
  ["dough", "ingredient"],
  ["drizzle", "action"],
  ["feather", "material"],
  ["finger", "body part"],
  ["flag", "object"],
  ["floor", "place"],
  ["flower", "plant"],
  ["foot", "body part"],
  ["game", "activity"],
  ["garden", "place"],
  ["gate", "object"],
  ["gift", "object"],
  ["glove", "clothing"],
  ["gold", "material"],
  ["grain", "food"],
  ["grass", "plant"],
  ["hat", "clothing"],
  ["head", "body part"],
  ["hill", "place"],
  ["honey", "food"],
  ["horse", "animal"],
  ["ice", "material"],
  ["idea", "concept"],
  ["island", "place"],
  ["jeans", "clothing"],
  ["juice", "beverage"],
  ["kite", "object"],
  ["kitten", "animal"],
  ["lamp", "object"],
  ["leaf", "plant"],
  ["letter", "object"],
  ["line", "shape"],
  ["lip", "body part"],
  ["love", "emotion"],
  ["lunch", "food"],
  ["map", "object"],
  ["mask", "object"],
  ["mirror", "object"],
  ["mittens", "clothing"],
  ["mouse", "animal"],
  ["neck", "body part"],
  ["nest", "place"],
  ["note", "object"],
  ["ocean", "nature"],
  ["oven", "device"],
  ["paint", "material"],
  ["pancake", "food"],
  ["paper", "material"],
  ["path", "place"],
  ["peach", "fruit"],
  ["pear", "fruit"],
  ["pen", "object"],
  ["petal", "plant"],
  ["phone", "object"],
  ["pillow", "object"],
  ["pizza", "food"],
  ["plant", "living organism"],
  ["plate", "object"],
  ["pocket", "clothing"],
  ["pond", "place"],
  ["post", "object"],
  ["present", "gift"],
  ["pumpkin", "plant"],
  ["puzzle", "game"],
  ["rain", "weather"],
  ["ribbon", "material"],
  ["ring", "object"],
  ["river", "nature"],
  ["road", "place"],
  ["roof", "structure"],
  ["root", "plant"],
  ["rug", "object"],
  ["salt", "material"],
  ["sand", "material"],
  ["seed", "plant"],
  ["shadow", "phenomenon"],
  ["sheep", "animal"],
  ["shell", "object"],
  ["shirt", "clothing"],
  ["shoe", "clothing"],
  ["sister", "person"],
  ["sky", "nature"],
  ["smile", "expression"],
  ["snow", "weather"],
  ["sock", "clothing"],
  ["song", "music"],
  ["spoon", "object"],
  ["spring", "season"],
  ["star", "celestial body"],
  ["stone", "material"],
  ["straw", "material"],
  ["stream", "nature"],
  ["string", "material"],
  ["sun", "celestial body"],
  ["table", "object"],
  ["tank", "object"],
  ["tent", "object"],
  ["thread", "material"],
  ["toast", "food"],
  ["tooth", "body part"],
  ["toy", "object"],
  ["tree", "plant"],
  ["tunnel", "place"],
  ["twig", "plant"],
  ["umbrella", "object"],
  ["valley", "place"],
  ["vase", "object"],
  ["veil", "clothing"],
  ["vine", "plant"],
  ["walk", "action"],
  ["wall", "structure"],
  ["water", "nature"],
  ["wave", "nature"],
  ["wheel", "object"],
  ["window", "object"],
  ["wing", "body part"],
  ["wood", "material"],
  ["wool", "material"],
  ["yard", "place"],
  ["yawn", "action"],
  ["zip", "object"],
  ["zoo", "place"],
  ["apple", "fruit"],
  ["bag", "object"],
  ["bench", "object"],
  ["bell", "object"],
  ["bird", "animal"],
  ["blanket", "object"],
  ["branch", "plant"],
  ["bridge", "structure"],
  ["bucket", "object"],
  ["button", "object"],
  ["card", "object"],
  ["ceiling", "structure"],
  ["cheese", "food"],
  ["chip", "food"],
  ["clam", "animal"],
  ["coin", "object"],
  ["corn", "food"],
  ["crown", "object"],
  ["cube", "object"],
  ["curl", "shape"],
  ["daisy", "plant"],
  ["deer", "animal"],
  ["dog", "animal"],
  ["donut", "food"],
  ["duck", "animal"],
  ["eagle", "animal"],
  ["earth", "nature"],
  ["eel", "animal"],
  ["egg", "food"],
  ["elbow", "body part"],
  ["fan", "object"],
  ["fence", "object"],
  ["fern", "plant"],
  ["fish", "animal"],
  ["flag", "object"],
  ["foam", "material"],
  ["fox", "animal"],
  ["friend", "person"],
  ["frog", "animal"],
  ["fruit", "food"],
  ["fry", "food"],
  ["gate", "object"],
  ["gem", "object"],
  ["giraffe", "animal"],
  ["glass", "material"],
  ["glue", "object"],
  ["goat", "animal"],
  ["goose", "animal"],
  ["gown", "clothing"],
  ["grass", "plant"],
  ["green", "color"],
  ["gum", "food"],
  ["hall", "place"],
  ["ham", "food"],
  ["hand", "body part"],
  ["hat", "clothing"],
  ["heart", "body part"],
  ["hen", "animal"],
  ["hill", "place"],
  ["hippo", "animal"],
  ["hole", "place"],
  ["home", "place"],
  ["horn", "body part"],
  ["horse", "animal"],
  ["hose", "object"],
  ["house", "place"],
  ["hug", "action"],
  ["ink", "material"],
  ["jar", "object"],
  ["jelly", "food"],
  ["jewel", "object"],
  ["jump", "action"],
  ["key", "object"],
  ["knee", "body part"],
  ["knot", "object"],
  ["lace", "material"],
  ["lamp", "object"],
  ["lemon", "fruit"],
  ["lid", "object"],
  ["lime", "fruit"],
  ["lion", "animal"],
  ["lip", "body part"],
  ["log", "nature"],
  ["mat", "object"],
  ["milk", "food"],
  ["moon", "nature"],
  ["mop", "object"],
  ["mug", "object"],
  ["nail", "body part"],
  ["napkin", "object"],
  ["net", "object"],
  ["nut", "food"],
  ["oak", "plant"],
  ["oil", "material"],
  ["owl", "animal"],
  ["pad", "object"],
  ["paint", "material"],
  ["palm", "plant"],
  ["paw", "body part"],
  ["pen", "object"],
  ["pencil", "object"],
  ["pin", "object"],
  ["pipe", "object"],
  ["pit", "place"],
  ["plum", "fruit"],
  ["pocket", "object"],
  ["pond", "nature"],
  ["pot", "object"],
  ["rain", "nature"],
  ["rat", "animal"],
  ["rice", "food"],
  ["rock", "nature"],
  ["roof", "structure"],
  ["rose", "plant"],
  ["rug", "object"],
  ["sand", "nature"],
  ["scoop", "object"],
  ["seed", "nature"],
  ["sew", "action"],
  ["shirt", "clothing"],
  ["shoe", "clothing"],
  ["shop", "place"],
  ["sister", "person"],
  ["soap", "object"],
  ["sock", "clothing"],
  ["spade", "object"],
  ["spin", "action"],
  ["spoon", "object"],
  ["spout", "object"],
  ["star", "nature"],
  ["stick", "object"],
  ["stone", "nature"],
  ["stream", "nature"],
  ["stripe", "pattern"],
  ["sun", "nature"],
  ["tank", "object"],
  ["tent", "object"],
  ["tile", "object"],
  ["toe", "body part"],
  ["tooth", "body part"],
  ["top", "clothing"],
  ["tree", "plant"],
  ["twig", "plant"],
  ["van", "vehicle"],
  ["vest", "clothing"],
  ["vow", "action"],
  ["walk", "action"],
  ["wall", "structure"],
  ["watch", "object"],
  ["water", "nature"],
  ["whale", "animal"],
  ["wheel", "object"],
  ["wing", "body part"],
  ["wire", "material"],
  ["wood", "material"],
  ["wool", "material"],
  ["yarn", "material"],
  ["zip", "object"],
  ["zoo", "place"],
  ["ant", "animal"],
  ["ball", "object"],
  ["bear", "animal"],
  ["bed", "furniture"],
  ["bike", "vehicle"],
  ["bird", "animal"],
  ["book", "object"],
  ["box", "object"],
  ["bus", "vehicle"],
  ["cake", "food"],
  ["cap", "clothing"],
  ["cat", "animal"],
  ["chair", "furniture"],
  ["cloud", "nature"],
  ["cow", "animal"],
  ["cup", "object"],
  ["desk", "furniture"],
  ["dog", "animal"],
  ["door", "structure"],
  ["egg", "food"],
  ["fan", "object"],
  ["fish", "animal"],
  ["flag", "object"],
  ["fox", "animal"],
  ["frog", "animal"],
  ["glove", "clothing"],
  ["goat", "animal"],
  ["gold", "material"],
  ["gum", "food"],
  ["hat", "clothing"],
  ["hen", "animal"],
  ["hill", "nature"],
  ["hook", "object"],
  ["jar", "object"],
  ["jeans", "clothing"],
  ["kite", "object"],
  ["leaf", "plant"],
  ["leg", "body part"],
  ["log", "nature"],
  ["map", "object"],
  ["mat", "object"],
  ["milk", "food"],
  ["net", "object"],
  ["nut", "food"],
  ["oak", "plant"],
  ["pen", "object"],
  ["pot", "object"],
  ["rag", "object"],
  ["rat", "animal"],
  ["rock", "nature"],
  ["rug", "object"],
  ["sun", "nature"],
  ["tape", "object"],
  ["tub", "object"],
  ["wall", "structure"],
  ["water", "nature"],
  ["whale", "animal"],
  ["wind", "nature"],
  ["wing", "body part"],
  ["wood", "material"],
  ["wool", "material"],
  ["yarn", "material"],
];

const WebSocket = require("ws");

const wss = new WebSocket.Server({ port: 8080 });
let rooms = {}; // Object to hold all game rooms and their players

// Function to update player count in a room
const updatePlayerCount = (roomId) => {
  const room = rooms[roomId];
  const playerNames = room.players.map((player) => player.name);
  const message = JSON.stringify({
    type: "playerCount",
    count: room.players.length,
    players: playerNames,
  });
  room.players.forEach((player) => player.ws.send(message));
};

wss.on("connection", (ws) => {
  ws.on("message", (message) => {
    const data = JSON.parse(message);

    if (data.type === "join") {
      const { roomId, playerName } = data;

      // Check if the room already exists or create a new one
      if (!rooms[roomId]) {
        rooms[roomId] = { players: [], admin: null };
        console.log(`New room created: ${roomId}`);
      }
      const room = rooms[roomId];
      const player = { ws, name: playerName, isAdmin: false };
      room.players.push(player);

      // Assign admin status to the first player in the room
      if (room.players.length === 1) {
        player.isAdmin = true;
        room.admin = player;
        ws.send(JSON.stringify({ type: "joined", isAdmin: true }));
      } else {
        ws.send(JSON.stringify({ type: "joined", isAdmin: false }));
      }

      // Notify all players in the room about the updated player count
      updatePlayerCount(roomId);
    }

    if (data.type === "start" && ws === rooms[data.roomId].admin?.ws) {
      let imposterCount = parseInt(data.imposterCount, 10);
      const room = rooms[data.roomId];
      const playersCount = room.players.length;

      // If the admin wants a random number of imposters, pick a random count
      if (data.randomImposter) {
        imposterCount = Math.floor(Math.random() * imposterCount) + 1; // Random number between 1 and the specified max
      }

      // Validate imposter count
      if (imposterCount >= playersCount) {
        ws.send(
          JSON.stringify({
            type: "error",
            message: "Imposter count is too high.",
          })
        );
        return;
      }
      const randomIndex = Math.floor(Math.random() * wordGenreArray.length);
      const chosenWord = wordGenreArray[randomIndex][0];
      const chosenGenre = wordGenreArray[randomIndex][1];
      const imposters = new Set();
      while (imposters.size < imposterCount) {
        const imposterIndex = Math.floor(Math.random() * room.players.length);
        imposters.add(room.players[imposterIndex]);
      }

      // Get names of imposters
      const imposterNames = Array.from(imposters).map((player) => player.name);

      // Send word to all players and reveal other imposters to the imposters
      room.players.forEach((player) => {
        if (imposters.has(player)) {
          player.ws.send(
            JSON.stringify({
              type: "gameStart",
              word: null, // Imposters don't get the word
              genre: data.genreCheck ? chosenGenre : null,
              imposters: imposterNames, // Reveal other imposters
            })
          );
        } else {
          player.ws.send(
            JSON.stringify({
              type: "gameStart",
              word: chosenWord, // Non-imposters get the word
              genre: data.genreCheck ? chosenGenre : null,
            })
          );
        }
      });
    }

    if (data.type === "nextGame" && ws === rooms[data.roomId].admin?.ws) {
      const room = rooms[data.roomId];
      let imposterCount = parseInt(data.imposterCount, 10);
      const randomIndex = Math.floor(Math.random() * wordGenreArray.length);
      const chosenWord = wordGenreArray[randomIndex][0];
      const chosenGenre = wordGenreArray[randomIndex][1];

      // If the admin wants a random number of imposters, pick a random count
      if (data.randomImposter) {
        imposterCount = Math.floor(Math.random() * imposterCount) + 1; // Random number between 1 and the specified max
      }

      const imposters = new Set();
      while (imposters.size < imposterCount) {
        const imposterIndex = Math.floor(Math.random() * room.players.length);
        imposters.add(room.players[imposterIndex]);
      }

      const imposterNames = Array.from(imposters).map((player) => player.name);

      // Send the new word and imposter information to all players
      room.players.forEach((player) => {
        if (imposters.has(player)) {
          player.ws.send(
            JSON.stringify({
              type: "gameStart",
              word: null,
              imposters: imposterNames,
              genre: data.genreCheck ? chosenGenre : null,
            })
          );
        } else {
          player.ws.send(
            JSON.stringify({
              type: "gameStart",
              word: chosenWord,
              genre: data.genreCheck ? chosenGenre : null,
            })
          );
        }
      });
    }
  });

  ws.on("close", () => {
    // Remove the player from all rooms
    Object.keys(rooms).forEach((roomId) => {
      rooms[roomId].players = rooms[roomId].players.filter(
        (player) => player.ws !== ws
      );

      // If the admin leaves, assign a new admin
      if (ws === rooms[roomId].admin?.ws && rooms[roomId].players.length > 0) {
        rooms[roomId].admin = rooms[roomId].players[0]; // The next player becomes the admin
        rooms[roomId].admin.isAdmin = true;
        rooms[roomId].admin.ws.send(
          JSON.stringify({ type: "joined", isAdmin: true })
        );
      }

      // Update player count and player list for all players in the room
      updatePlayerCount(roomId);
    });
  });
});

console.log("Server Started");
